# Домашнее задание 2 - предобработка признаков, pandas


### О задании

Практическое задание 2 посвящено изучению основных библиотек для анализа данных, а также линейных моделей и методов их обучения. Вы научитесь:
 * применять библиотеки NumPy и Pandas для осуществления желаемых преобразований;
 * подготавливать данные для обучения линейных моделей;
 * обучать линейную, Lasso и Ridge-регрессии при помощи модуля scikit-learn;
 * реализовывать обычный и стохастический градиентные спуски;
 * обучать линейную регрессию для произвольного функционала качества.
 

### Оценивание и штрафы

Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи). Максимально допустимая оценка за работу — 10 баллов. Кроме того, некоторые из заданий являются опциональными (необязательными), однако за их выполнение можно получить дополнительные баллы, которые позднее будут учитываться при проставлении оценок автоматом по курсу.

Сдавать задание после указанного срока сдачи нельзя. При выставлении неполного балла за задание в связи с наличием ошибок на усмотрение проверяющего предусмотрена возможность исправить работу на указанных в ответном письме условиях.

Задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов. Если вы нашли решение какого-то из заданий (или его часть) в открытом источнике, необходимо указать ссылку на этот источник в отдельном блоке в конце Вашей работы (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник). 

Неэффективная реализация кода может негативно отразиться на оценке.


### Формат сдачи
Для сдачи задания получившийся файл \*.ipynb с решением необходимо выложить в свой репозиторий github.

## Библиотеки для анализа данных

### NumPy

Во всех заданиях данного раздела запрещено использовать циклы  и list comprehensions. Под вектором и матрицей в данных заданиях понимается одномерный и двумерный numpy.array соответственно.

In [53]:
import numpy as np

**1. (0.2 балла)** Реализуйте функцию, возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответом является 5. Если нулевых элементов нет, функция должна возвращать None.


In [54]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x = np.append(x, -1)

In [55]:
def max_element(arr):
    zero_indexes = np.where(arr == 0)[0]
    if len(zero_indexes) == 0:
        return None
    next_indexes = zero_indexes + 1
    next_elements = arr[next_indexes]
    max_element = np.max(next_elements)
    return max_element
max_element(x)


5

**2. (0.2 балла)** Реализуйте функцию, принимающую на вход матрицу и некоторое число и возвращающую ближайший к числу элемент матрицы. Например: для X = np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4.

In [56]:
def nearest_value(X, v):
    # Your code here
#     abs_list = list(map(lambda item: abs(item - v), X)) # создаем список значений разницы item - value по модулю 
#     return X[abs_list.index(min(abs_list))]  

    flattened_matrix = X.flatten()  # преобразуем матрицу к одномерному массиву
    idx = (np.abs(flattened_matrix - v)).argmin()  # находим индекс элемента с минимальной разницей
    return flattened_matrix[idx]  # возвращаем ближайший элемент

X = np.arange(0,10).reshape((2, 5))
nearest_value(X, 3.6)

4

**3. (0.2 балла)** Реализуйте функцию scale(X), которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает выборочное среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на случайной матрице (для её генерации можно использовать, например, функцию [numpy.random.randint](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html)).

In [57]:
def scale(X):
    # Your code here
    Xscaled = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
    return Xscaled

# Пример использования функции
X = np.random.randint(0, 10, size=(5, 3))
Xscaled = scale(X)
print(Xscaled)

[[-1.50589393  0.70710678 -0.98473193]
 [-0.87843813  1.41421356 -0.98473193]
 [ 1.00392929  0.          0.86164044]
 [ 0.69020139 -1.41421356  1.47709789]
 [ 0.69020139 -0.70710678 -0.36927447]]


**4. (0.2 балла)** Реализуйте функцию, которая для заданной матрицы находит:
 - определитель
 - след
 - наименьший и наибольший элементы
 - норму Фробениуса
 - собственные числа
 - обратную матрицу

Для тестирования сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}$(10,1)

In [58]:
def get_stats(X):
    # Your code here
    
    # Определитель
    det = np.linalg.det(X)
    
    # След
    trace = np.trace(X)
    
    # Наименьший и наибольший элементы
    min_element = np.min(X)
    max_element = np.max(X)
    
    # Норма Фробениуса
    norm = np.linalg.norm(X, 'fro')
    
    # Собственные числа
    eigenvalues = np.linalg.eigvals(X)
    
    # Обратная матрица
    try:
        inverse = np.linalg.inv(X)
    except np.linalg.LinAlgError:
        print("Матрица является вырожденной, обратной матрицы не существует")
        return None
    
    return det, trace, min_element, max_element, norm, eigenvalues, inverse

# Создание матрицы с элементами из нормального распределения (10, 1)
X = np.random.normal(10, 1, (3, 3))

# Вызов функции для анализа матрицы
result = get_stats(matrix)

# Вывод результатов
print("Определитель:", result[0])
print("След:", result[1])
print("Наименьший элемент:", result[2])
print("Наибольший элемент:", result[3])
print("Норма Фробениуса:", result[4])
print("Собственные числа:", result[5])
print("Обратная матрица:\n", result[6])

Определитель: 21.38674600072864
След: 29.877092753297326
Наименьший элемент: 8.532490836235118
Наибольший элемент: 10.927222742540213
Норма Фробениуса: 28.692204317477927
Собственные числа: [28.63292384+0.j         0.62208446+0.5999495j  0.62208446-0.5999495j]
Обратная матрица:
 [[ 0.87038563 -0.04209425 -0.68298046]
 [-1.26615578  0.64825543  0.50258588]
 [ 0.47105459 -0.57293085  0.18199737]]


**5. (0.2 балла)** Повторите 100 раз следующий эксперимент: сгенерируйте две матрицы размера 10×10 из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

In [59]:
max_values = []
for exp_num in range(100):
    # Your code here

    matrix1 = np.random.randn(10, 10)
    matrix2 = np.random.randn(10, 10)
    product = np.dot(matrix1, matrix2)
    max_value = np.max(product)
    
    max_values.append(max_value)

average_max = np.mean(max_values)
quantile_95 = np.percentile(max_values, 95)

print("Среднее значение максимальных элементов:", average_max)
print("95-процентная квантиль:", quantile_95)

Среднее значение максимальных элементов: 8.224676976072464
95-процентная квантиль: 11.403726592628015


### Pandas

![](https://metrouk2.files.wordpress.com/2015/10/panda.jpg)

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные находятся в приложенном файле `2008.csv`. Их [описание](http://stat-computing.org/dataexpo/2009/the-data.html) приведено ниже:

Airline on-time performance

Have you ever been stuck in an airport because your flight was delayed or cancelled and wondered if you could have predicted it if you'd had more data? This is your chance to find out.

The data
The data set is available for download here.
The data consists of flight arrival and departure details for all commercial flights within the USA, from October 1987 to April 2008. This is a large dataset: there are nearly 120 million records in total, and takes up 1.6 gigabytes of space compressed and 12 gigabytes when uncompressed.

Understanding and preparing the data
In order to answer above questions, we are going to analyze the provided dataset, containing up to 1936758 ### different internal flights in the US for 2008 and their causes for delay, diversion and cancellation

The data comes from the U.S. Department of Transportation’s (DOT) Bureau of Transportation Statistics (BTS). Meta data explanations

This dataset is composed by the following variables:

**Year** 2008 **Month** 1-12 **DayofMonth** 1-31 **DayOfWeek** 1 (Monday) - 7 (Sunday)  
**DepTime** actual departure time (local, hhmm)  
**CRSDepTime** scheduled departure time (local, hhmm)  
**ArrTime** actual arrival time (local, hhmm)  
**CRSArrTime** scheduled arrival time (local, hhmm)  
**UniqueCarrier** unique carrier code  
**FlightNum** flight number  
**TailNum** plane tail number: aircraft registration, unique aircraft identifier  
**ActualElapsedTime** in minutes  
**CRSElapsedTime** in minutes  
**AirTime** in minutes  
**ArrDelay** arrival delay, in minutes: A flight is counted as “on time” if it operated less than 15 minutes later the scheduled time shown in the carriers’ Computerized Reservations Systems (CRS).  
**DepDelay** departure delay, in minutes  
**Origin** origin IATA airport code  
**Dest** destination IATA airport code  
**Distance** in miles  
**TaxiIn** taxi in time, in minutes  
**TaxiOut** taxi out time in minutes  
**Cancelled** *was the flight cancelled  
**CancellationCode** reason for cancellation (A = carrier, B = weather, C = NAS, D = security)  
**Diverted** 1 = yes, 0 = no  
**CarrierDelay** in minutes: Carrier delay is within the control of the air carrier. Examples of occurrences that may determine carrier delay are: aircraft cleaning, aircraft damage, awaiting the arrival of connecting passengers or crew, baggage, bird strike, cargo loading, catering, computer, outage-carrier equipment, crew legality (pilot or attendant rest), damage by hazardous goods, engineering inspection, fueling, handling disabled passengers, late crew, lavatory servicing, maintenance, oversales, potable water servicing, removal of unruly passenger, slow boarding or seating, stowing carry-on baggage, weight and balance delays.  
**WeatherDelay** in minutes: Weather delay is caused by extreme or hazardous weather conditions that are forecasted or manifest themselves on point of departure, enroute, or on point of arrival.  
**NASDelay** in minutes: Delay that is within the control of the National Airspace System (NAS) may include: non-extreme weather conditions, airport operations, heavy traffic volume, air traffic control, etc.  
**SecurityDelay** in minutes: Security delay is caused by evacuation of a terminal or concourse, re-boarding of aircraft because of security breach, inoperative screening equipment and/or long lines in excess of 29 minutes at screening areas.  
**LateAircraftDelay** in minutes: Arrival delay at an airport due to the late arrival of the same aircraft at a previous airport. The ripple effect of an earlier delay at downstream airports is referred to as delay propagation.

In [60]:
import pandas as pd
%matplotlib inline

In [61]:
data = pd.read_csv('2008.csv')
data

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime   
0      2008      6          18          3   2111.0        2055   2308.0  \
1      2008      6           4          3   1426.0        1410   1730.0   
2      2008      8           3          7   1143.0        1145   1501.0   
3      2008      1          23          3   1141.0        1144   1323.0   
4      2008      5           4          7    815.0         820   1243.0   
...     ...    ...         ...        ...      ...         ...      ...   
69995  2008      5          12          1   1829.0        1840   2137.0   
69996  2008      5          11          7   1149.0        1125   1336.0   
69997  2008      9          24          3   1012.0        1012   1132.0   
69998  2008      2          18          1   1906.0        1900   2200.0   
69999  2008     12           6          6    859.0         900    959.0   

       CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled   
0            2300            WN        242  ...    3.0      8.0          0  \
1            1728            XE       2380  ...    4.0     12.0          0   
2            1520            WN       1769  ...    4.0      9.0          0   
3            1335            OO       3802  ...    4.0     19.0          0   
4            1300            WN        399  ...    4.0      8.0          0   
...           ...           ...        ...  ...    ...      ...        ...   
69995        2149            DL        794  ...   22.0     20.0          0   
69996        1314            OO       6159  ...    4.0     13.0          0   
69997        1132            YV       7058  ...    7.0     10.0          0   
69998        2139            NW        641  ...   20.0     22.0          0   
69999        1005            WN        510  ...    2.0     12.0          0   

       CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay   
0                   NaN         0           NaN          NaN      NaN  \
1                   NaN         0           NaN          NaN      NaN   
2                   NaN         0           NaN          NaN      NaN   
3                   NaN         0           NaN          NaN      NaN   
4                   NaN         0           NaN          NaN      NaN   
...                 ...       ...           ...          ...      ...   
69995               NaN         0           NaN          NaN      NaN   
69996               NaN         0           0.0          0.0      0.0   
69997               NaN         0           NaN          NaN      NaN   
69998               NaN         0           0.0          0.0     15.0   
69999               NaN         0           NaN          NaN      NaN   

       SecurityDelay  LateAircraftDelay  
0                NaN                NaN  
1                NaN                NaN  
2                NaN                NaN  
3                NaN                NaN  
4                NaN                NaN  
...              ...                ...  
69995            NaN                NaN  
69996            0.0               22.0  
69997            NaN                NaN  
69998            0.0                6.0  
69999            NaN                NaN  

[70000 rows x 29 columns]

**6. (0.3 балла)** Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)

In [62]:
# Your code here

cancelled_flights = data['CancellationCode'].value_counts()
cancelled_winner = cancelled_flights.idxmax()
print(cancelled_winner, ' - "carrier" reason')

A  - "carrier" reason


**7. (0.3 балла)** Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.

In [63]:
# Your code here
mean_dist = data['Distance'].mean()
min_dist = data['Distance'].min()
max_dist = data['Distance'].max()
print("Расстояние, пройденные самолетами в милях:")
print('Среднее: ', mean_dist)
print('Минимальное: ', min_dist)
print('Максимальное: ', max_dist)

Расстояние, пройденные самолетами в милях:
Среднее:  724.5082571428571
Минимальное:  31
Максимальное:  4962


**8. (0.3 балла)** Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?

In [64]:
# Your code here
# Отфильтровать данные для получения записей с минимальным пройденным расстоянием
min_distance = data[data['Distance'] == data['Distance'].min()]

# Вывести данные с минимальным пройденным расстоянием
print("Записи с минимальным пройденным расстоянием:")
print(min_distance[['Year',  'Month',  'DayofMonth',  'DayOfWeek', 'Distance']], "\n")

# Получить уникальные значения рейсов с минимальным пройденным расстоянием
unique_flights = min_distance['FlightNum'].unique()

# Отфильтровать данные только для этих рейсов
filtered_data = data[data['FlightNum'].isin(unique_flights)]

# Вывести данные для этих рейсов
print("Данные для рейсов с минимальным пройденным расстоянием:")
print(filtered_data)

Записи с минимальным пройденным расстоянием:
       Year  Month  DayofMonth  DayOfWeek  Distance
1116   2008     12          30          2        31
6958   2008     12          26          5        31
17349  2008      8          18          1        31
27534  2008      3          11          2        31
46082  2008      8           9          6        31
48112  2008      2          28          4        31 

Данные для рейсов с минимальным пройденным расстоянием:
       Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime   
501    2008      3          20          4   1253.0        1252   1427.0  \
1116   2008     12          30          2   1123.0        1007   1148.0   
1389   2008      3          13          4   1748.0        1804   2048.0   
1517   2008      7          10          4    733.0         730    837.0   
2619   2008      5          23          5   1612.0        1605     29.0   
...     ...    ...         ...        ...      ...         ...      ...   
66529  2

**9. (0.3 балла)** Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?

In [65]:
# Your code here

# Подсчет количества вылетов из каждого аэропорта
departure_counts = data["Origin"].value_counts()

# Получение аэропорта с наибольшим количеством вылетов
max_departure_airport = departure_counts.idxmax()

# Вывод результата
print("Аэропорт с наибольшим количеством вылетов:", max_departure_airport)


Аэропорт с наибольшим количеством вылетов: ATL


**10. (0.3 балла)** Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?

In [66]:
# Your code here
# Группировка данных по аэропортам и вычисление среднего значения "AirTime"
average_airtime = data.groupby("Origin")["AirTime"].mean()

# Нахождение аэропорта с наибольшим средним значением "AirTime"
airport_max_airtime = average_airtime.idxmax()
airport_max_airtime

'SJU'

**11. (0.5 балла)** Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [67]:
# Your code here
# Группировка и подсчет рейсов
grouped = data.groupby('Origin').agg({'FlightNum': 'count', 'DepDelay': lambda x: (x > 0).sum()})

# Фильтрация по количеству рейсов
filtered = grouped[grouped['FlightNum'] >= 1000]

# Расчет доли задержанных рейсов
filtered['DelayRatio'] = filtered['DepDelay'] / filtered['FlightNum']

# Нахождение аэропорта с наибольшей долей задержанных рейсов
airport_with_max_delay_ratio = filtered['DelayRatio'].idxmax()

print("Аэропорт с наибольшей долей задержанных рейсов: ", airport_with_max_delay_ratio)

Аэропорт с наибольшей долей задержанных рейсов:  EWR


C:\Users\79689\AppData\Local\Temp\ipykernel_28660\4114212466.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['DelayRatio'] = filtered['DepDelay'] / filtered['FlightNum']


## Линейная регрессия

В этой части мы разберемся с линейной регрессией, способами её обучения и измерением качества ее прогнозов. 

Будем рассматривать датасет из предыдущей части задания для предсказания времени задержки отправления рейса в минутах (DepDelay). Отметим, что под задержкой подразумевается не только опоздание рейса относительно планируемого времени вылета, но и отправление до планируемого времени.

### Подготовка данных

**12. (0.5 балла)** Считайте выборку из файла при помощи функции pd.read_csv и ответьте на следующие вопросы:
   - Имеются ли в данных пропущенные значения?
   - Сколько всего пропущенных элементов в таблице "объект-признак"?
   - Сколько объектов имеют хотя бы один пропуск?
   - Сколько признаков имеют хотя бы одно пропущенное значение?

In [ ]:
# Your code here

Как вы понимаете, также не имеет смысла рассматривать при решении поставленной задачи объекты с пропущенным значением целевой переменной. В связи с этим ответьте на следующие вопросы и выполните соответствующие действия:
- Имеются ли пропущенные значения в целевой переменной?
- Проанализируйте объекты с пропущенными значениями целевой переменной. Чем вызвано это явление? Что их объединяет? Можно ли в связи с этим, на ваш взгляд, исключить какие-то признаки из рассмотрения? Обоснуйте свою точку зрения.

Исключите из выборки объекты **с пропущенным значением целевой переменной и со значением целевой переменной, равным 0**, а также при необходимости исключите признаки в соответствии с вашим ответом на последний вопрос из списка и выделите целевую переменную в отдельный вектор, исключив её из матрицы "объект-признак".

In [ ]:
# Your code here

**13. (0.5 балла)** Обратите внимание, что признаки DepTime, CRSDepTime, ArrTime, CRSArrTime приведены в формате hhmm, в связи с чем будет не вполне корректно рассматривать их как вещественные.

Преобразуйте каждый признак FeatureName из указанных в пару новых признаков FeatureName\_Hour, FeatureName\_Minute, разделив каждое из значений на часы и минуты. Не забудьте при этом исключить исходный признак из выборки. В случае, если значение признака отсутствует, значения двух новых признаков, его заменяющих, также должны отсутствовать. 

Например, признак DepTime необходимо заменить на пару признаков DepTime_Hour, DepTime_Minute. При этом, например, значение 155 исходного признака будет преобразовано в значения 1 и 55 признаков DepTime_Hour, DepTime_Minute соответственно.

In [ ]:
# Your code here

**14. (0.5 балла)** Некоторые из признаков, отличных от целевой переменной, могут оказывать чересчур значимое влияние на прогноз, поскольку по своему смыслу содержат большую долю информации о значении целевой переменной. Изучите описание датасета и исключите признаки, сильно коррелирующие с ответами. Ваш выбор признаков для исключения из выборки обоснуйте. Кроме того, исключите признаки TailNum и Year.

In [ ]:
# Your code here

**15. (1 балл)** Приведем данные к виду, пригодному для обучения линейных моделей. Для этого вещественные признаки надо отмасштабировать, а категориальные — привести к числовому виду. Также надо устранить пропуски в данных.

В первую очередь поймем, зачем необходимо применять масштабирование. Следующие ячейки с кодом построят гистограммы для 3 вещественных признаков выборки.

In [ ]:
X['DepTime_Hour'].hist(bins=20)

In [ ]:
X['TaxiIn'].hist(bins=20)

In [ ]:
X['FlightNum'].hist(bins=20)

Какую проблему вы наблюдаете на этих графиках? Как масштабирование поможет её исправить?

Некоторые из признаков в нашем датасете являются категориальными. Типичным подходом к работе с ними является бинарное, или [one-hot-кодирование](https://en.wikipedia.org/wiki/One-hot).

Реализуйте функцию transform_data, которая принимает на вход DataFrame с признаками и выполняет следующие шаги:
1. Замена пропущенных значений на нули для вещественных признаков и на строки 'nan' для категориальных.
2. Масштабирование вещественных признаков с помощью [StandardScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).
3. One-hot-кодирование категориальных признаков с помощью [DictVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.DictVectorizer.html) или функции [pd.get_dummies](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html).

Метод должен возвращать преобразованный DataFrame, который должна состоять из масштабированных вещественных признаков и закодированных категориальных (исходные признаки должны быть исключены из выборки).

In [ ]:
def transform_data(data):
    # Your code here

Примените функцию transform_data к данным. Сколько признаков получилось после преобразования?

In [ ]:
# Your code here

**16. (0.5 балла)** Разбейте выборку и вектор целевой переменной на обучение и контроль в отношении 70/30 (для этого можно использовать, например, функцию [train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.train_test_split.html)). 

In [ ]:
# Your code here

### Scikit-learn

<img src = "https://pp.vk.me/c4534/u35727827/93547647/x_d31c4463.jpg">
Теперь, когда мы привели данные к пригодному виду, попробуем решить задачу при помощи метода наименьших квадратов. Напомним, что данный метод заключается в оптимизации функционала $MSE$:

$$MSE(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 \to \min_{w},$$

где $\{ (x_i, y_i ) \}_{i=1}^l$ — обучающая выборка, состоящая из $l$ пар объект-ответ.

Заметим, что решение данной задачи уже реализовано в модуле sklearn в виде класса [LinearRegression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression).

**17. (0.5 балла)** Обучите линейную регрессию на 1000 объектах из обучающей выборки и выведите значения $MSE$ и $R^2$ на этой подвыборке и контрольной выборке (итого 4 различных числа). Проинтерпретируйте полученный результат — насколько качественные прогнозы строит полученная модель? Какие проблемы наблюдаются в модели?

**Подсказка**: изучите значения полученных коэффициентов $w$, сохраненных в атрибуте coef_ объекта LinearRegression.

In [ ]:
# Your code here

Для решения описанных вами в предыдущем пункте проблем используем L1- или L2-регуляризацию, тем самым получив Lasso и Ridge регрессии соответственно и изменив оптимизационную задачу одним из следующих образов:
$$MSE_{L1}(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 + \alpha ||w||_1 \to \min_{w},$$
$$MSE_{L2}(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 + \alpha ||w||_2^2 \to \min_{w},$$

где $\alpha$ — коэффициент регуляризации. Один из способов его подбора заключается в переборе некоторого количества значений и оценке качества на кросс-валидации для каждого из них, после чего выбирается значение, для которого было получено наилучшее качество.

In [ ]:
# Your code here

**18. (1 балл)**__ Обучение линейной регрессии.



Обучите линейную регрессию с $L_1$ (Lasso) и $L_2$ (Ridge) регуляризаторами (используйте параметры по умолчанию). Посмотрите, какое количество коэффициентов близко к 0 (степень близости к 0 определите сами из разумных пределов). Постройте график зависимости числа ненулевых коэффициентов от коэффицента регуляризации (перебирайте значения по логарифмической сетке от $10^{-3}$ до $10^3$). Согласуются ли результаты с вашими ожиданиями?

In [ ]:
# Your code here
# ...

Посчитайте для Ridge-регрессии следующие метрики: $RMSE$, $MAE$, $R^2$.

In [ ]:
# Your code here
# ...

Подберите на обучающей выборке для Ridge-регрессии коэффициент регуляризации (перебирайте значения по логарифмической сетке от $10^{-3}$ до $10^3$) для каждой из метрик при помощи кросс-валидации c 5 фолдами на тех же 1000 объектах. Для этого воспользуйтесь GridSearchCV и KFold из sklearn. Постройте графики зависимости фукнции потерь от коэффициента регуляризации. Посчитайте те же метрики снова. Заметно ли изменилось качество?

Для выполнения данного задания вам могут понадобиться реализованные в библиотеке объекты [LassoCV](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html), [RidgeCV](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html) и [KFold](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.KFold.html).

In [1]:
# Your code here
# ...
print('hello world!')

hello world!


__19. (0.5 балла)__ Поиск объектов-выбросов


Как известно, MSE сильно штрафует за большие ошибки на объектах-выбросах. С помощью cross_val_predict сделайте Out-of-Fold предсказания для обучающей выборки. Посчитайте ошибки и посмотрите на их распределение (plt.hist). Что вы видите?